### ISSUE TITLE
recoverey key works and your typec fix is not complete

### ISSUE THREAD

**Issue by Shaggy013** [Depau/alarm-orangepi4#1]
recoverey key works and your typec fix is not complete

to have recovery work you have to enable the key in uboot and make a recovery structure 

and your type c fix is not complete , for example on boot type c does not have power ;)

ow and the pcie is not 4x but only 2x to the connector and the board is just 1x 

so i dont know who is talking about ducktape 

first make a proper dtb  for kernel and uboot ;) because opi has no pwm3 or what i said about pcie 
switching C12 does give typec 5 v 
or if you reenable the 1.8v rail even fusb comes on .
little same as pinebook just make a board file

**Comment by depau** [comment]
> recoverey key works and your typec fix is not complete
> 
> to have recovery work you have to enable the key in uboot and make a recovery structure

Good to know.

> and your type c fix is not complete , for example on boot type c does not have power ;)

You mean in u-boot or linux early boot? The u-boot code has seen very little effort. Also the rest of the code, before you go ahead and say that.

> ow and the pcie is not 4x but only 2x to the connector and the board is just 1x

I didn't touch the PCIe code, that's all from Armbian. For what it's worth, I use it and it works, and that's why I didn't touch it.

> so i dont know who is talking about ducktape

![sticker webp](https://user-images.githubusercontent.com/1151321/111534310-21e5f800-8768-11eb-9be8-e7f2ddd0f048.png)
![sticker1 webp](https://user-images.githubusercontent.com/1151321/111534316-227e8e80-8768-11eb-807a-b8aa74b71ecb.png)
![sticker2 webp](https://user-images.githubusercontent.com/1151321/111534318-23172500-8768-11eb-81ac-ccdec8884258.png)

> first make a proper dtb for kernel and uboot ;) because opi has no pwm3 or what i said about pcie

Also good to know.

> switching C12 does give typec 5 v
> or if you reenable the 1.8v rail even fusb comes on .

Good to know.

> little same as pinebook just make a board file

In general, it seems like you know how the thingy works so if instead of taking it personally you'd use the "Pull requests" button above, or even better submit it to Linux for inclusion upstream, that'd be great ;)

No claims are made on the quality or accuracy of this code and FWIW 99% of this code is from Armbian. The remaining 1% is me spending a weekend trying to figure out why the orange pi would shut down cause someone thought it was a good idea to remove thermal restrictions, or why it would randomly not boot cause someone thought it was a good idea to set the eMMC to the highest rate :P

![mp4](https://user-images.githubusercontent.com/1151321/111535074-fe6f7d00-8768-11eb-817d-9b7ea5a6a7cf.gif)
